"use strict";
// Switch baseline configuration generator.
// Architecture: Open/Closed Principle — add vendors by registering in VENDOR_GENERATORS.
// No existing generator is modified when adding a new vendor.
// All generators are pure functions: params in → { vendor, commands, config, notes } out.

const { isValidHost } = require("./validate");

const SUPPORTED_VENDORS = [
  "cisco-ios",
  "cisco-nxos",
  "allied-telesis",
  "mikrotik",
  "fortinet",
  "juniper",
  "generic"
];

// ── Input validation ──────────────────────────────────────────────────────────

const SUBNET_MASK_RE = /^(255|254|252|248|240|224|192|128|0)(\.(255|254|252|248|240|224|192|128|0)){3}$/;

function validateParams(params) {
  const errors = [];
  if (!params.hostname || !/^[A-Za-z0-9_-]{1,64}$/.test(params.hostname)) {
    errors.push("hostname: must be 1-64 chars (A-Z, 0-9, hyphen, underscore)");
  }
  if (params.vendor && !SUPPORTED_VENDORS.includes(String(params.vendor).toLowerCase())) {
    errors.push(`vendor: unknown vendor "${params.vendor}". Supported: ${SUPPORTED_VENDORS.join(", ")}`);
  }
  if (params.mgmtIp && !isValidHost(params.mgmtIp)) {
    errors.push("mgmtIp: must be a valid IPv4 address or hostname");
  }
  if (params.mgmtMask && !SUBNET_MASK_RE.test(params.mgmtMask) && !/^\d{1,2}$/.test(params.mgmtMask)) {
    errors.push("mgmtMask: must be a valid dotted-quad subnet mask (e.g. 255.255.255.0) or CIDR prefix (e.g. 24)");
  }
  if (params.gateway && !isValidHost(params.gateway)) {
    errors.push("gateway: must be a valid IPv4 address or hostname");
  }
  if (params.ntpServer && !isValidHost(params.ntpServer) &&
      !/^[a-z0-9.-]+\.[a-z]{2,}$/i.test(params.ntpServer)) {
    errors.push("ntpServer: must be a valid IP or FQDN");
  }
  if (params.vlans !== undefined && !Array.isArray(params.vlans)) {
    errors.push("vlans: must be an array of { id, name? } objects");
  }
  for (const v of (params.vlans || [])) {
    const id = Number(v.id);
    if (!Number.isInteger(id) || id < 1 || id > 4094) {
      errors.push(`vlans: VLAN ID ${v.id} is out of range (1-4094)`);
    }
  }
  return errors;
}

// ── Shared helpers ────────────────────────────────────────────────────────────

function _cidr(mask) {
  if (!mask) return 24;
  if (/^\d{1,2}$/.test(mask)) return Number(mask);
  const parts = String(mask).split(".");
  let bits = 0;
  for (const p of parts) {
    let n = parseInt(p, 10);
    while (n > 0) { bits += n & 1; n >>>= 1; }
  }
  return bits || 24;
}

function _safeName(name) {
  return String(name || "").replace(/[^A-Za-z0-9_-]/g, "_").slice(0, 32);
}

// ── Cisco IOS / IOS-XE ───────────────────────────────────────────────────────

function generateCiscoIOS(p) {
  const vlans = p.vlans || [];
  const out   = [
    "! ═══════════════════════════════════════════════════",
    "! Baseline — Cisco IOS / IOS-XE",
    `! Generated by Ahuva IT Support Assistant`,
    "! ═══════════════════════════════════════════════════",
    "configure terminal",
    `hostname ${p.hostname}`,
    "!",
    "no service pad",
    "service timestamps debug datetime msec localtime",
    "service timestamps log datetime msec localtime",
    "service password-encryption",
    "no ip domain-lookup",
    "!"
  ];

  if (p.enableSecret) {
    out.push(`enable secret ${p.enableSecret}`, "!");
  }
  if (p.adminUser && p.adminPass) {
    out.push(`username ${p.adminUser} privilege 15 secret ${p.adminPass}`, "!");
  }

  // VLANs
  for (const v of vlans) {
    out.push(`vlan ${v.id}`);
    if (v.name) out.push(` name ${_safeName(v.name)}`);
    out.push("!");
  }

  // Management SVI
  if (p.mgmtVlan && p.mgmtIp && p.mgmtMask) {
    out.push(`interface Vlan${p.mgmtVlan}`,
             ` description Management`,
             ` ip address ${p.mgmtIp} ${p.mgmtMask}`,
             " no shutdown", "!");
    if (p.gateway) out.push(`ip default-gateway ${p.gateway}`, "!");
  }

  // SSH hardening
  if (p.sshDomain || p.adminUser) {
    out.push(
      `ip domain-name ${p.sshDomain || "corp.local"}`,
      "crypto key generate rsa modulus 2048",
      "ip ssh version 2",
      "ip ssh time-out 60",
      "ip ssh authentication-retries 3", "!",
      "line vty 0 4",
      " transport input ssh",
      p.adminUser ? " login local" : " login",
      " exec-timeout 10 0", "!"
    );
  }

  if (p.ntpServer) out.push(`ntp server ${p.ntpServer}`, "!");
  if (p.bannerMotd) {
    const msg = String(p.bannerMotd).replace(/\^/g, "");
    out.push(`banner motd ^${msg}^`, "!");
  }

  out.push(
    "logging buffered 16384 informational",
    "logging console critical",
    p.syslogServer ? `logging host ${p.syslogServer}` : null,
    p.snmpCommunity ? `snmp-server community ${p.snmpCommunity} RO` : null,
    "!",
    "end",
    "write memory",
    "! ═══════════════════════════════════════════════════"
  );

  const config = out.filter(l => l !== null).join("\n");
  const commands = out.filter(l => l !== null && !l.startsWith("!")).map(l => l.trim()).filter(Boolean);

  return {
    vendor: "cisco-ios",
    config,
    commands,
    notes: [
      "Adjust management VLAN and SVI interface numbers to match your hardware.",
      "RSA key generation may require a few seconds and a reload on older IOS.",
      "Use a strong enable secret — minimum 12 characters, mixed case + digits."
    ]
  };
}

// ── Cisco NX-OS ──────────────────────────────────────────────────────────────

function generateCiscoNXOS(p) {
  const vlans = p.vlans || [];
  const out   = [
    "! ═══════════════════════════════════════════════════",
    "! Baseline — Cisco NX-OS",
    "! ═══════════════════════════════════════════════════",
    "configure terminal",
    `hostname ${p.hostname}`,
    "feature ssh",
    "feature scp-server",
    "no feature telnet", "!"
  ];

  if (p.adminUser && p.adminPass) {
    out.push(`username ${p.adminUser} password ${p.adminPass} role network-admin`, "!");
  }

  for (const v of vlans) {
    out.push(`vlan ${v.id}`);
    if (v.name) out.push(`  name ${_safeName(v.name)}`);
    out.push("  exit");
  }

  if (p.mgmtIp) {
    const cidr = _cidr(p.mgmtMask);
    out.push(`interface mgmt0`,
             `  ip address ${p.mgmtIp}/${cidr}`,
             "  no shutdown", "!");
  }

  if (p.gateway)   out.push(`ip route 0.0.0.0/0 ${p.gateway}`, "!");
  if (p.ntpServer) out.push(`ntp server ${p.ntpServer}`, "!");

  out.push("end", "copy running-config startup-config");
  out.push("! ═══════════════════════════════════════════════════");

  const config   = out.join("\n");
  const commands = out.filter(l => !l.startsWith("!")).map(l => l.trim()).filter(Boolean);

  return {
    vendor: "cisco-nxos",
    config,
    commands,
    notes: [
      "NX-OS uses CIDR notation (/24) not dotted-quad masks.",
      "Feature activation may cause brief traffic interruption on first enable.",
      "Run 'feature nxapi' only if REST management is required."
    ]
  };
}

// ── Allied Telesis AW+ ────────────────────────────────────────────────────────

function generateAlliedTelesis(p) {
  const vlans = p.vlans || [];
  const out   = [
    "! ═══════════════════════════════════════════════════",
    "! Baseline — Allied Telesis AW+",
    "! ═══════════════════════════════════════════════════",
    `set system name "${p.hostname}"`, "!"
  ];

  if (vlans.length) {
    out.push("vlan database");
    for (const v of vlans) {
      out.push(`  vlan ${v.id}${v.name ? " name " + _safeName(v.name) : ""}`);
    }
    out.push("exit", "!");
  }

  if (p.mgmtVlan && p.mgmtIp && p.mgmtMask) {
    const cidr = _cidr(p.mgmtMask);
    out.push(`interface vlan${p.mgmtVlan}`,
             ` ip address ${p.mgmtIp}/${cidr}`,
             " no shutdown", "exit", "!");
  }

  if (p.gateway) out.push(`ip route 0.0.0.0/0 ${p.gateway}`, "!");

  if (p.adminUser && p.adminPass) {
    out.push(`username ${p.adminUser} privilege 15 password ${p.adminPass}`, "!");
  }

  out.push("service ssh");
  if (p.ntpServer) out.push(`ntp server ${p.ntpServer}`);
  out.push("write memory");
  out.push("! ═══════════════════════════════════════════════════");

  const config   = out.join("\n");
  const commands = out.filter(l => !l.startsWith("!")).map(l => l.trim()).filter(Boolean);

  return {
    vendor: "allied-telesis",
    config,
    commands,
    notes: [
      "Allied Telesis uses CIDR notation. Adjust interface names per hardware (e.g. port1.0.1).",
      "For patch releases, use 'awplus# install license' before deploying SSH keys."
    ]
  };
}

// ── MikroTik RouterOS ─────────────────────────────────────────────────────────

function generateMikroTik(p) {
  const vlans = p.vlans || [];
  const out   = [
    "# ═══════════════════════════════════════════════════",
    "# Baseline — MikroTik RouterOS",
    "# ═══════════════════════════════════════════════════",
    `/system identity set name="${p.hostname}"`
  ];

  for (const v of vlans) {
    out.push(`/interface vlan add name=vlan${v.id} vlan-id=${v.id} interface=bridge comment="${v.name || ""}"`);
  }

  if (p.mgmtIp && p.mgmtMask) {
    const cidr = _cidr(p.mgmtMask);
    out.push(`/ip address add address=${p.mgmtIp}/${cidr} interface=bridge`);
  }

  if (p.gateway)   out.push(`/ip route add gateway=${p.gateway}`);
  if (p.ntpServer) out.push(`/system ntp client set enabled=yes server-dns-names=${p.ntpServer}`);

  if (p.adminUser && p.adminPass) {
    out.push(`/user add name=${p.adminUser} password="${p.adminPass}" group=full`);
  }

  out.push(
    "/ip service disable telnet,ftp,www,api,api-ssl",
    "/ip service enable ssh"
  );
  out.push("# ═══════════════════════════════════════════════════");

  const config   = out.join("\n");
  const commands = out.filter(l => !l.startsWith("#")).map(l => l.trim()).filter(Boolean);

  return {
    vendor: "mikrotik",
    config,
    commands,
    notes: [
      "Replace 'interface=bridge' with your actual bridge interface name.",
      "MikroTik commands use forward-slash path prefixes — do not omit them.",
      "Disable default admin account after creating your own: /user disable admin"
    ]
  };
}

// ── Fortinet FortiGate ────────────────────────────────────────────────────────

function generateFortiGate(p) {
  const vlans = p.vlans || [];
  const out   = [
    "# ═══════════════════════════════════════════════════",
    "# Baseline — Fortinet FortiGate",
    "# ═══════════════════════════════════════════════════",
    "config system global",
    `  set hostname ${p.hostname}`,
    "end"
  ];

  for (const v of vlans) {
    out.push(
      "config system interface",
      `  edit "vlan${v.id}"`,
      "    set vdom root",
      "    set type vlan",
      `    set vlanid ${v.id}`,
      v.name ? `    set alias "${v.name}"` : null,
      "  next",
      "end"
    );
  }

  if (p.adminUser && p.adminPass) {
    out.push(
      "config system admin",
      `  edit "${p.adminUser}"`,
      `    set password ${p.adminPass}`,
      '    set accprofile "super_admin"',
      "  next",
      "end"
    );
  }

  if (p.ntpServer) {
    out.push(
      "config system ntp",
      "  set ntpsync enable",
      `  set server "${p.ntpServer}"`,
      "end"
    );
  }

  out.push("# ═══════════════════════════════════════════════════");

  const config   = out.filter(l => l !== null).join("\n");
  const commands = out.filter(l => l !== null && !l.startsWith("#")).map(l => l.trim()).filter(Boolean);

  return {
    vendor: "fortinet",
    config,
    commands,
    notes: [
      "FortiGate VLANs need a parent physical interface. Add 'set interface <port>' inside the vlan block.",
      "Management IP is configured under 'config system interface' for the management port.",
      "Run 'execute backup config flash' after applying baseline."
    ]
  };
}

// ── Juniper JunOS ─────────────────────────────────────────────────────────────

function generateJuniper(p) {
  const vlans = p.vlans || [];
  const out   = [
    "# ═══════════════════════════════════════════════════",
    "# Baseline — Juniper JunOS",
    "# ═══════════════════════════════════════════════════",
    `set system host-name ${p.hostname}`,
    "set system services ssh protocol-version v2",
    "set system services ssh max-sessions-per-connection 2"
  ];

  if (p.adminUser && p.adminPass) {
    out.push(`set system login user ${p.adminUser} class super-user`);
    out.push(`set system login user ${p.adminUser} authentication plain-text-password "${p.adminPass}"`);
  }

  for (const v of vlans) {
    const vName = v.name ? _safeName(v.name) : `vlan${v.id}`;
    out.push(`set vlans ${vName} vlan-id ${v.id}`);
    if (p.mgmtVlan && String(v.id) === String(p.mgmtVlan) && p.mgmtIp && p.mgmtMask) {
      out.push(`set vlans ${vName} l3-interface irb.${v.id}`);
      out.push(`set interfaces irb unit ${v.id} family inet address ${p.mgmtIp}/${_cidr(p.mgmtMask)}`);
    }
  }

  if (p.gateway)   out.push(`set routing-options static route 0.0.0.0/0 next-hop ${p.gateway}`);
  if (p.ntpServer) out.push(`set system ntp server ${p.ntpServer}`);

  out.push("commit check", "commit");
  out.push("# ═══════════════════════════════════════════════════");

  const config   = out.join("\n");
  const commands = out.filter(l => !l.startsWith("#")).map(l => l.trim()).filter(Boolean);

  return {
    vendor: "juniper",
    config,
    commands,
    notes: [
      "JunOS uses 'commit check' to validate before committing — never skip it.",
      "IRB interface numbers must match VLAN IDs for consistent L3 addressing.",
      "Rollback is easy: 'rollback 1 && commit' to revert the last commit."
    ]
  };
}

// ── Generic template ──────────────────────────────────────────────────────────

function generateGeneric(p) {
  const vlans = p.vlans || [];
  const out   = [
    `# ═══════════════════════════════════════════════════`,
    `# Generic Switch Baseline — review commands for your vendor`,
    `# ═══════════════════════════════════════════════════`,
    `# Step 1: Hostname`,
    `hostname ${p.hostname}`
  ];

  if (vlans.length) {
    out.push("# Step 2: VLANs");
    for (const v of vlans) {
      out.push(`vlan ${v.id}`);
      if (v.name) out.push(` name ${_safeName(v.name)}`);
    }
  }

  if (p.mgmtIp) {
    out.push(`# Step 3: Management IP`,
             `interface vlan ${p.mgmtVlan || 1}`,
             ` ip address ${p.mgmtIp} ${p.mgmtMask || "255.255.255.0"}`);
  }

  if (p.gateway)   out.push(`# Step 4: Default gateway`, `ip default-gateway ${p.gateway}`);
  if (p.adminUser) out.push(`# Step 5: Admin user`, `username ${p.adminUser} password ${p.adminPass || "CHANGE_ME"}`);

  out.push("# Step 6: Save", "write memory");
  out.push("# ═══════════════════════════════════════════════════");

  const config   = out.join("\n");
  const commands = out.filter(l => !l.startsWith("#")).map(l => l.trim()).filter(Boolean);

  return {
    vendor: "generic",
    config,
    commands,
    notes: [
      "This is a generic template. Review every command against your vendor's CLI reference.",
      "VLAN syntax varies: Cisco/AW+ use 'vlan <id>', MikroTik uses /interface vlan, FortiGate uses config system interface."
    ]
  };
}

// ── Public API ────────────────────────────────────────────────────────────────

const VENDOR_GENERATORS = {
  "cisco-ios":      generateCiscoIOS,
  "cisco-nxos":     generateCiscoNXOS,
  "allied-telesis": generateAlliedTelesis,
  "mikrotik":       generateMikroTik,
  "fortinet":       generateFortiGate,
  "juniper":        generateJuniper,
  "generic":        generateGeneric
};

/**
 * Generate a baseline configuration for a new switch.
 * @param {object} params
 * @returns {{ vendor: string, config: string, commands: string[], notes: string[] }}
 * @throws {Error} if params fail validation
 */
function generateBaseline(params) {
  const errors = validateParams(params);
  if (errors.length) throw new Error("Validation failed:\n• " + errors.join("\n• "));
  const key = String(params.vendor || "generic").toLowerCase();
  const gen = VENDOR_GENERATORS[key] || VENDOR_GENERATORS.generic;
  return gen(params);
}

module.exports = { generateBaseline, validateParams, SUPPORTED_VENDORS };
